"""Add hidden flag to companies and read_hidden permission to API keys

Revision ID: 8d4c2d09abc1
Revises: 625ffc4ec744
Create Date: 2026-01-09 15:48:50.871842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4c2d09abc1'
down_revision = '625ffc4ec744'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default value first to handle existing data
    op.add_column('api_keys', sa.Column('read_hidden', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('companies', sa.Column('hidden', sa.Boolean(), server_default='false', nullable=False))

    # Drop the unique constraint on name alone
    op.drop_index('ix_companies_name', table_name='companies')

    # Create new indexes
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index('ix_companies_name_hidden', 'companies', ['name', 'hidden'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_name_hidden', table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index('ix_companies_name', 'companies', ['name'], unique=True)
    op.drop_column('companies', 'hidden')
    op.drop_column('api_keys', 'read_hidden')
    # ### end Alembic commands ###
